plugins:
  - jekyll-relative-links
  - jeykll-menu
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - responsibilities.md
  - values.md
  - resources.md
theme: jekyll-theme-minimal
